-- MySQL Script generated by MySQL Workbench
-- Wed Mar 24 19:17:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Onlex
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Onlex
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Onlex` ;
USE `Onlex` ;

-- -----------------------------------------------------
-- Table `Onlex`.`Membre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Onlex`.`Membre` (
  `email` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Onlex`.`Inscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Onlex`.`Inscription` (
  `idInscription` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Membre_email` VARCHAR(45) NOT NULL,
  `ville` VARCHAR(45) NULL,
  `telephone` INT NULL,
  `CNE` VARCHAR(45) NULL,
  `dateNaissance` DATE NULL,
  `adresse` VARCHAR(45) NULL,
  `sexe` VARCHAR(20) NULL,
  `ecole` VARCHAR(45) NULL,
  `typeDeConcours` VARCHAR(20) NULL,
  `diplome` BLOB NULL,
  `releveDeNotes` BLOB NULL,
  `ecoleDeChoix` VARCHAR(45) NULL,
  `img1` BLOB NULL,
  `img2` BLOB NULL,
  `img3` BLOB NULL,
  PRIMARY KEY (`idInscription`, `Membre_email`),
  INDEX `fk_Inscription_Membre_idx` (`Membre_email` ASC) VISIBLE,
  CONSTRAINT `fk_Inscription_Membre`
    FOREIGN KEY (`Membre_email`)
    REFERENCES `Onlex`.`Membre` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Onlex`.`Questionnaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Onlex`.`Questionnaire` (
  `idQuestionnaire` INT NOT NULL AUTO_INCREMENT,
  `dateOuverture` DATE NOT NULL,
  `duree` FLOAT NOT NULL,
  PRIMARY KEY (`idQuestionnaire`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Onlex`.`Concours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Onlex`.`Concours` (
  `idConcours` INT NOT NULL AUTO_INCREMENT,
  `ecole` VARCHAR(45) NULL,
  `dateDepot` DATE NULL,
  `dateFin` DATE NULL,
  `idQuestionnaire` INT NOT NULL,
  PRIMARY KEY (`idConcours`, `idQuestionnaire`),
  INDEX `fk_Concours_Questionnaire1_idx` (`idQuestionnaire` ASC) VISIBLE,
  CONSTRAINT `fk_Concours_Questionnaire1`
    FOREIGN KEY (`idQuestionnaire`)
    REFERENCES `Onlex`.`Questionnaire` (`idQuestionnaire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Onlex`.`Candidat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Onlex`.`Candidat` (
  `idCandidat` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Membre_email` VARCHAR(45) NOT NULL,
  `idConcours` INT NOT NULL,
  `ville` VARCHAR(45) NULL,
  `telephone` INT NULL,
  `CNE` VARCHAR(45) NULL,
  `dateNaissance` DATE NULL,
  `adresse` VARCHAR(45) NULL,
  `sexe` VARCHAR(20) NULL,
  `ecole` VARCHAR(45) NULL,
  PRIMARY KEY (`idCandidat`, `Membre_email`, `idConcours`),
  INDEX `fk_Inscription_Membre_idx` (`Membre_email` ASC) VISIBLE,
  INDEX `fk_Candidat_Concours1_idx` (`idConcours` ASC) VISIBLE,
  CONSTRAINT `fk_Inscription_Membre0`
    FOREIGN KEY (`Membre_email`)
    REFERENCES `Onlex`.`Membre` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Candidat_Concours1`
    FOREIGN KEY (`idConcours`)
    REFERENCES `Onlex`.`Concours` (`idConcours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Onlex`.`DossierDeCandidature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Onlex`.`DossierDeCandidature` (
  `idDossier` INT NOT NULL AUTO_INCREMENT,
  `Candidat_email` VARCHAR(45) NOT NULL,
  `typeDeConcours` VARCHAR(20) NULL,
  `diplome` BLOB NULL,
  `releveDeNotes` BLOB NULL,
  `ecoleDeChoix` VARCHAR(45) NULL,
  PRIMARY KEY (`idDossier`, `Candidat_email`),
  INDEX `fk_DossierDeCandidature_Candidat1_idx` (`Candidat_email` ASC) VISIBLE,
  CONSTRAINT `fk_DossierDeCandidature_Candidat1`
    FOREIGN KEY (`Candidat_email`)
    REFERENCES `Onlex`.`Candidat` (`Membre_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Onlex`.`CaptureFaciale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Onlex`.`CaptureFaciale` (
  `idCapture` INT NOT NULL AUTO_INCREMENT,
  `Candidat_email` VARCHAR(45) NOT NULL,
  `img1` BLOB NULL,
  `img2` BLOB NULL,
  `img3` BLOB NULL,
  PRIMARY KEY (`idCapture`, `Candidat_email`),
  INDEX `fk_CaptureFaciale_Candidat1_idx` (`Candidat_email` ASC) VISIBLE,
  CONSTRAINT `fk_CaptureFaciale_Candidat1`
    FOREIGN KEY (`Candidat_email`)
    REFERENCES `Onlex`.`Candidat` (`Membre_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Onlex`.`Note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Onlex`.`Note` (
  `idNote` INT NOT NULL AUTO_INCREMENT,
  `idCandidat` INT UNSIGNED NOT NULL,
  `Candidat_email` VARCHAR(45) NOT NULL,
  `idConcours` INT NOT NULL,
  `note` FLOAT NOT NULL,
  PRIMARY KEY (`idNote`),
  INDEX `fk_Note_Candidat1_idx` (`idCandidat` ASC, `Candidat_email` ASC, `idConcours` ASC) VISIBLE,
  CONSTRAINT `fk_Note_Candidat1`
    FOREIGN KEY (`idCandidat` , `Candidat_email` , `idConcours`)
    REFERENCES `Onlex`.`Candidat` (`idCandidat` , `Membre_email` , `idConcours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Onlex`.`Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Onlex`.`Question` (
  `idQuestion` INT NOT NULL AUTO_INCREMENT,
  `intitule` VARCHAR(45) NOT NULL,
  `typeDeReponse` VARCHAR(20) NULL,
  `point` FLOAT NOT NULL,
  PRIMARY KEY (`idQuestion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Onlex`.`Option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Onlex`.`Option` (
  `idOption` INT NOT NULL AUTO_INCREMENT,
  `idQuestion` INT NOT NULL,
  `texte` VARCHAR(45) NOT NULL,
  `verdict` TINYINT NULL,
  PRIMARY KEY (`idOption`, `idQuestion`),
  INDEX `fk_Option_Question1_idx` (`idQuestion` ASC) VISIBLE,
  CONSTRAINT `fk_Option_Question1`
    FOREIGN KEY (`idQuestion`)
    REFERENCES `Onlex`.`Question` (`idQuestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Onlex`.`Questionnaire_has_Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Onlex`.`Questionnaire_has_Question` (
  `idQuestionnaire` INT NOT NULL AUTO_INCREMENT,
  `idQuestion` INT NOT NULL,
  PRIMARY KEY (`idQuestionnaire`, `idQuestion`),
  INDEX `fk_Questionnaire_has_Question_Question1_idx` (`idQuestion` ASC) VISIBLE,
  INDEX `fk_Questionnaire_has_Question_Questionnaire1_idx` (`idQuestionnaire` ASC) VISIBLE,
  CONSTRAINT `fk_Questionnaire_has_Question_Questionnaire1`
    FOREIGN KEY (`idQuestionnaire`)
    REFERENCES `Onlex`.`Questionnaire` (`idQuestionnaire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Questionnaire_has_Question_Question1`
    FOREIGN KEY (`idQuestion`)
    REFERENCES `Onlex`.`Question` (`idQuestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Onlex`.`Reponse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Onlex`.`Reponse` (
  `idReponse` INT NOT NULL AUTO_INCREMENT,
  `idCandidat` INT UNSIGNED NULL,
  `Candidat_email` VARCHAR(45) NOT NULL,
  `idQuestionnaire` INT NOT NULL,
  `idQuestion` INT NOT NULL,
  `idOption` INT NOT NULL,
  `reponse` VARCHAR(45) NULL,
  `note` FLOAT NULL,
  PRIMARY KEY (`idReponse`, `Candidat_email`, `idQuestionnaire`, `idQuestion`, `idOption`),
  INDEX `fk_Reponse_Candidat1_idx` (`idCandidat` ASC, `Candidat_email` ASC) VISIBLE,
  INDEX `fk_Reponse_Option1_idx` (`idOption` ASC, `idQuestion` ASC) VISIBLE,
  INDEX `fk_Reponse_Questionnaire1_idx` (`idQuestionnaire` ASC) VISIBLE,
  CONSTRAINT `fk_Reponse_Candidat1`
    FOREIGN KEY (`idCandidat` , `Candidat_email`)
    REFERENCES `Onlex`.`Candidat` (`idCandidat` , `Membre_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reponse_Option1`
    FOREIGN KEY (`idOption` , `idQuestion`)
    REFERENCES `Onlex`.`Option` (`idOption` , `idQuestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reponse_Questionnaire1`
    FOREIGN KEY (`idQuestionnaire`)
    REFERENCES `Onlex`.`Questionnaire` (`idQuestionnaire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Onlex`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Onlex`.`Admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `Pseudo` VARCHAR(45) NOT NULL,
  `password` TEXT NOT NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Onlex`.`Annonce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Onlex`.`Annonce` (
  `idAnnonce` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`idAnnonce`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
